INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (2, 'Amerikanske dollar', 'USD');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (3, 'Australske dollar', 'AUD');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (4, 'Brasilianske real', 'BRL');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (5, 'Britiske pund', 'GBP');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (6, 'Bulgarske lev', 'BGN');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (7, 'Canadiske dollar', 'CAD');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (8, 'Danske kroner', 'DKK');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (9, 'Euro', 'EUR');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (10, 'Filippinske peso', 'PHP');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (11, 'Hongkong dollar', 'HKD');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (12, 'Indiske rupee', 'INR');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (13, 'Indonesiske rupiah', 'IDR');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (14, 'Islandske kroner *', 'ISK');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (15, 'Israelske shekel', 'ILS');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (16, 'Japanske yen', 'JPY');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (17, 'Kinesiske Yuan renminbi', 'CNY');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (18, 'Malaysiske ringgit', 'MYR');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (19, 'Mexicanske peso', 'MXN');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (20, 'New Zealandske dollar', 'NZD');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (21, 'Norske kroner', 'NOK');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (22, 'Polske zloty', 'PLN');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (23, 'Rumænske lei', 'RON');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (24, 'Schweiziske franc', 'CHF');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (25, 'Singapore dollar', 'SGD');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (26, 'Svenske kroner', 'SEK');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (27, 'Sydafrikanske rand', 'ZAR');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (28, 'Sydkoreanske won', 'KRW');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (29, 'Thailandske baht', 'THB');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (30, 'Tjekkiske koruna', 'CZK');
INSERT INTO public.currencies (currencyid, currencyname, currencysymbol) VALUES (31, 'Tyrkiske lira', 'TRY');
